name: deco
channels:
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=0.9.0=py37_0
  - astor=0.8.0=py37_0
  - blas=1.0=mkl
  - c-ares=1.15.0=h1de35cc_1001
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_1
  - gast=0.2.2=py37_0
  - google-pasta=0.2.0=py_0
  - grpcio=1.16.1=py37h044775b_1
  - h5py=2.10.0=py37h3134771_0
  - hdf5=1.10.4=hfa1e0ec_0
  - intel-openmp=2019.4=233
  - keras=2.3.1=0
  - keras-applications=1.0.8=py_0
  - keras-base=2.3.1=py37_0
  - keras-preprocessing=1.1.0=py_1
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libprotobuf=3.11.4=hd9629dc_0
  - markdown=3.1.1=py37_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.15=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - ncurses=6.2=h0a44026_0
  - numpy=1.18.1=py37h7241aed_0
  - numpy-base=1.18.1=py37h6575580_1
  - openssl=1.1.1f=h1de35cc_0
  - opt_einsum=3.1.0=py_0
  - pandas=1.0.3=py37h6c726b0_0
  - pip=20.0.2=py37_1
  - protobuf=3.11.4=py37h0a44026_0
  - python=3.7.7=hc70fcce_0_cpython
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pyyaml=5.3.1=py37h1de35cc_0
  - readline=8.0=h1de35cc_0
  - scipy=1.4.1=py37h9fa6033_0
  - setuptools=46.1.3=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=ha441bb4_0
  - tensorboard=2.0.0=pyhb38c66f_1
  - tensorflow=2.0.0=mkl_py37hda344b4_0
  - tensorflow-base=2.0.0=mkl_py37h66b1bf0_0
  - tensorflow-estimator=2.0.0=pyh2649769_0
  - termcolor=1.1.0=py37_1
  - tk=8.6.8=ha441bb4_0
  - tqdm=4.44.1=py_0
  - werkzeug=1.0.0=py_0
  - wheel=0.34.2=py37_0
  - wrapt=1.12.1=py37h1de35cc_1
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - aif360==0.2.3
    - joblib==0.14.1
    - pyaml==20.4.0
    - scikit-learn==0.22.2.post1
    - scikit-optimize==0.7.4
prefix: /Users/author/anaconda3/envs/deco

